---
# tasks file for sshkeyprivesc
- name: Add the user 
  ansible.builtin.user:
    name: "{{sshkeyprivesc_user}}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  tags:
    - user
    - key

- name: Insecure .ssh-permissions
  ansible.builtin.file:
    path: "/home/{{sshkeyprivesc_user}}/.ssh"
    mode: 0755
  tags:
    - key
    - vuln

- name: Insecure ssh-key permissions
  ansible.builtin.file:
    path: "/home/{{sshkeyprivesc_user}}/.ssh/id_rsa"
    mode: 0704
  tags:
    - key
    - vuln

- name: Install root-key
  block:
    - name: Read public-key
      ansible.builtin.shell:
        cmd: "cat /home/{{sshkeyprivesc_user}}/.ssh/id_rsa.pub"
      register: pubkey

    - name: Write public-key
      ansible.builtin.lineinfile:
        path: /root/.ssh/authorized_keys
        line: "{{pubkey.stdout}}"
  tags:
    - key
    - vuln

